channels:
- conda-forge
- bioconda
- defaults
dependencies:
- bioconda::bioconductor-edger=4.0.16
- bioconda::bioconductor-ihw=1.28.0
- bioconda::bioconductor-limma=3.58.1
- conda-forge::r-dplyr=1.1.4
- conda-forge::r-readr=2.1.5
